import { describe, expect, it } from "vitest";
import { conversationDetail, turnStateOf } from "../src/lib/client/real-api";
// Generated by the backend from its canonical models (contracts/examples.json).
import examples from "../../contracts/examples.json";

type Detail = Parameters<typeof conversationDetail>[0];
const example = examples.operations.get_conversation.response as Detail;

describe("conversation turns, from the persisted run only", () => {
  it("maps the generated example: a queued turn is waiting, not replied", () => {
    const d = conversationDetail(example);
    expect(d.messages).toEqual([
      expect.objectContaining({
        author: "person",
        text: "Help me think this through",
        origin: "human",
        sequence: 1,
      }),
    ]);
    expect(d.turns[0]).toMatchObject({
      run_id: example.runs[0]!.id,
      message_id: example.messages[0]!.id,
    });
    expect(d.turns[0]!.state).toBe(
      turnStateOf(example.runs[0]!, example.messages),
    );
  });

  it("needs a recorded assistant message before calling a ready turn replied", () => {
    const run = { id: "r", state: "ready" as const };
    expect(turnStateOf(run, [])).toBe("no_reply");
    expect(
      turnStateOf(run, [{ run_id: "r", author_kind: "assistant" as const }]),
    ).toBe("replied");
    expect(
      turnStateOf(run, [{ run_id: "r", author_kind: "human" as const }]),
    ).toBe("no_reply");
  });

  it("maps queued, running and cancelled exactly", () => {
    expect(turnStateOf({ id: "r", state: "queued" }, [])).toBe("queued");
    expect(turnStateOf({ id: "r", state: "running" }, [])).toBe("responding");
    expect(turnStateOf({ id: "r", state: "cancelled" }, [])).toBe("cancelled");
  });

  it("orders messages by sequence, not by arrival", () => {
    const m = example.messages[0]!;
    const d = conversationDetail({
      ...example,
      messages: [
        {
          ...m,
          id: "b",
          sequence: 2,
          author_kind: "assistant",
          evidence_origin: "controlled_transport",
        },
        m,
      ],
    });
    expect(d.messages.map((x) => x.sequence)).toEqual([1, 2]);
    expect(d.messages[1]).toMatchObject({
      author: "agent",
      origin: "controlled_transport",
    });
  });
});
