import { describe, expect, it } from "vitest";
import {
  hasManagedGroup,
  recommendationFrom,
} from "../src/lib/client/recommendation";
import type { Block } from "../src/lib/contract/types";
// Generated by the backend's own `responses_schema.to_body` (initial run, then
// a revision over a saved human edit), not hand-written shapes.
import bodies from "./fixtures/managed-bodies.json";

type Wire = { block_id: string; kind: string; text: string };
const view = (body: { blocks: Wire[] }): Block[] =>
  body.blocks.map((b) => ({
    id: b.block_id,
    kind: "paragraph",
    text: b.text,
    backend_kind: "paragraph",
  }));

describe("recommendation from the current managed group", () => {
  it("reads the initial worker document's substance, not a placeholder", () => {
    const r = recommendationFrom(view(bodies.initial));
    expect(r.summary).toBe(
      "Run a private eight-case owner and next-action check before changing the intake form.",
    );
    expect(r.summary).not.toBe("Review the saved work");
    expect(r.evidence).toEqual([
      "SG-F2@1: Intake log: 4 of 8 cases lack an owner or next action.",
      "SG-F3@1: Method notebook: test one change before automating.",
    ]);
    expect(r.uncertainty).toEqual([
      "Who owns the review date for the next eight cases?",
      "Whether case P4 is still open.",
    ]);
    expect(r.judgment).toBe(
      "Decide whether the eight-case check is worth one hour this week.",
    );
  });

  it("lets the current group win over earlier managed groups kept in history", () => {
    const blocks = view(bodies.revision);
    const r = recommendationFrom(blocks);
    expect(r.summary).toMatch(/^Check the next eight cases/);
    expect(r.evidence).toEqual([
      "SG-F2@1: Intake log: union of missing owner/next action is 4 of 8.",
    ]);
    expect(r.uncertainty).toEqual(["Confirm the recorded review date."]);
    expect(r.evidence.join(" ")).not.toMatch(/Method notebook/);
    // The original human note is retained in the document below the history marker.
    expect(blocks.some((b) => b.id === "human-1")).toBe(true);
  });

  it("only advances after the revision is the saved document", () => {
    // Until the person accepts it, the saved body is the base: earlier advice stands.
    const base = view(bodies.initial).concat({
      id: "human-1",
      kind: "paragraph",
      text: "Keep Wednesday 14:00–15:00 for method drafting.",
    });
    expect(recommendationFrom(base).summary).toMatch(/^Run a private/);
  });

  it("keeps the fixture document fallback for older records", () => {
    const fixture: Block[] = [
      { id: "recommendation", kind: "paragraph", text: "Test one check." },
      { id: "evidence", kind: "list_item", text: "4 of 8 cases." },
      { id: "unknowns", kind: "paragraph", text: "No time-saved data." },
    ];
    expect(hasManagedGroup(fixture)).toBe(false);
    expect(recommendationFrom(fixture)).toEqual({
      summary: "Test one check.",
      evidence: ["4 of 8 cases."],
      uncertainty: ["No time-saved data."],
    });
  });

  it("never drops substance when a heading prefix is absent", () => {
    const blocks: Block[] = [
      { id: "managed.current.x", kind: "paragraph", text: "Current proposal" },
      { id: "managed.next-action.x", kind: "paragraph", text: "Do one thing." },
    ];
    expect(recommendationFrom(blocks).summary).toBe("Do one thing.");
  });
});
